project_id = "pmewgcolyowqqokfzxwp"

[functions.create-checkout-session]
verify_jwt = true

[functions.get-script]
verify_jwt = true

[functions.list-scripts]
verify_jwt = true

[functions.generate-custom-script]
verify_jwt = true
